### ISSUE TITLE
kali下执行会报错“错误: 找不到或无法加载主类 UI.Main”

### ISSUE THREAD

**Issue by ybdt** [SafeGroceryStore/MDAT#1]
使用的版本是
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
是版本问题吗？

**Comment by Ch1ngg** [comment]
这边测试可以正常打开
![image](https://user-images.githubusercontent.com/17949373/104574711-4e5e9480-5691-11eb-9395-5302bb99b3b0.png)
Java 版本
```
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```

**Comment by kaliisra** [comment]
我也是，在kali和win各个版本都不行ui.MAIN

**Comment by Ch1ngg** [comment]
> 我也是，在kali和win各个版本都不行ui.MAIN

应该是 jdk 版本问题，已知 jdk 11 已经把 javafx 移除，请使用 jdk 8尝试(不是OpenJdk)。

**Comment by ybdt** [comment]
经测试，下载oracle的jdk8不会报错，可下载oracle的compressd版jdk8
