### ISSUE TITLE
开放源码

### ISSUE THREAD

**Issue by yezi-m4c1** [SafeGroceryStore/MDAT#3]
大佬什么时候开放源码，想学习学习用javafx怎么写工具

**Comment by Ch1ngg** [comment]
后续会公开，只是现在还没定好整体框架，还有就是现在代码写的太丑了o(╥﹏╥)o

**Comment by yezi-m4c1** [comment]
哈哈哈，我写的代码也丑，有时候还恬不知耻的修改别人的代码。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SafeGroceryStore/MDAT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月18日(星期四) 中午1:28
收件人:&nbsp;"SafeGroceryStore/MDAT"<MDAT@noreply.github.com&gt;;
抄送:&nbsp;"1153400561"<www.com1.8@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SafeGroceryStore/MDAT] 开放源码 (#3)





 
后续会公开，只是现在还没定好整体框架，还有就是现在代码写的太丑了o(╥﹏╥)o
